wsgi/shopping/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from . import views

from mezzanine.conf import settings

_slash = "/" if settings.APPEND_SLASH else ""

urlpatterns = patterns("shopping.views",
                       url("^product/(?P<slug>.*)%s$" % _slash, views.product, name="shop_product"),
                       url(r'^(?P<product_id>\d{1,2})/$', views.productDetail, name="detail"),
                       url(r'^like_product/$', views.like_product, name='like_product'),

                       )

wsgi/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from profiles.forms import SignupFormWithCaptcha


admin.autodiscover()

from account.views import ChangePasswordView, SignupView, LoginView

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    #url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    url(r"^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),
    
    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!
    url(r'^detail/', include('shopping.urls', namespace="shopping")),
    url(r"^accounts/signup/$", SignupView.as_view(form_class=SignupFormWithCaptcha), name="registration_register"),
    url(r'^accounts/', include('account.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^forum/', include('pybb.urls', namespace='pybb')),
    ("^shop/", include("cartridge.shop.urls")),
    url("^account/orders/$", "cartridge.shop.views.order_history",
        name="shop_order_history"),

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

    #url(r'^shop/', include('shopping.urls', namespace="shopping")),


)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

wsgi/shopping/models.py
from cartridge.shop.models import Sale, Product
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mezzanine.core.fields import FileField
from mezzanine.core.models import RichText
from mezzanine.pages.models import Page
from mezzanine.utils.models import upload_to
from pybb.models import Forum
from shopping.managers import NewSaleManager


class HomePage(Page, RichText):

    '''
    A page representing the format of the home page
    '''

    class Meta:
        verbose_name = _("Home page")
        verbose_name_plural = _("Home pages")


class ExtendForum(models.Model):
    forum = models.OneToOneField(Forum)
    image = FileField(verbose_name=_("Image"),
                      upload_to=upload_to("pybb.forum.image", "image"),
                      format="Image", max_length=255, null=True, blank=True)


class MySale(Sale):
    secondary = NewSaleManager()

    class Meta:
        proxy = True


class ProductExtend:
    def show_discount_percent(self):
        result = 100 - int((self.sale_price/self.unit_price)*100)
        return result

Product.__bases__ += (ProductExtend,)

wsgi/shopping/views.py
from cartridge.shop.models import Product, ProductImage, ProductVariation
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template import RequestContext

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)


def product(request, slug):
    return HttpResponse("Hello, world. You're at the poll index.")
#from wsgi.shopping.models import Product, ProductImage, ProductVariation


def productDetail(request, product_id):

    product = get_object_or_404(Product, pk=product_id)
    viewed_product_list = []
    if product:
        views = product.view + 1
        product.view = views
        product.save()
        if not 'viewedProducts' in request.session or not request.session['viewedProducts']:
            request.session['viewedProducts'] = [product_id]
        else:
            viewedProducts = request.session['viewedProducts']
            index = 0
            for id in viewedProducts:
                if product_id == id:
                    break
                if index == len(viewedProducts)-1:
                    viewedProducts.append(product_id)
                    break
                index += 1
                
            request.session['viewedProduct'] = viewedProducts
            index = 0
            for id in reversed(viewedProducts):
                product = Product.objects.get(id=id)
                viewed_product_list.append(product)
                index += 1
                if index == 4:
                    break


    product_image_list = ProductImage.objects.filter(product_id=product_id)
    product_option_list = ProductVariation.objects.filter(product_id=product_id)


    return render(request, "pages/product_detail.html", {"product": product,
                  "product_image_list": product_image_list,
                  "product_option_list": product_option_list,
                  # "viewedProducts": viewedProducts
                  "viewed_product_list": viewed_product_list
    })


@login_required
def like_product(request):
    product_id = None
    if request.method == 'GET':
        product_id = request.GET['product_id']

    if product_id:
        product = Product.objects.get(id=product_id)
        if product:
            is_liked = "is_liked" + product_id
            checkLiked = request.session.get(is_liked, False)
            if(checkLiked):
                likes = product.like - 1
                response = HttpResponse(likes)
                request.session[is_liked] = False
            else:
                likes = product.like + 1
                response = HttpResponse(likes)
                request.session[is_liked] = True
            product.like = likes
            product.save()
            # print is_liked
    return response

wsgi/shopping/templates/pages/category.html
{% extends "pages/page.html" %}

{% load mezzanine_tags shop_tags i18n %}
{#{% block body_id %}category{% endblock %}#}
{##}
{#{% block all_content %}{{ block.super }}#}
{##}
{#{% editable page.category.content %}#}
{#{{ page.category.content|safe }}#}
{#{% endeditable %}#}
{##}
{#{% if child_categories %}#}
{#<div class="row shop-category-list">#}
{#{% if settings.SHOP_CATEGORY_USE_FEATURED_IMAGE %}#}
{#    {% for category in child_categories %}#}
{#    <div class="col-xs-6 col-sm-4 col-lg-3">#}
{#    <a href="{{ category.get_absolute_url }}" class="thumbnail">#}
{#        {% if category.featured_image %}#}
{#        <img src="{{ MEDIA_URL }}{% thumbnail category.featured_image 148 148 %}" />#}
{#        {% else %}#}
{#        <div class="placeholder"></div>#}
{#        {% endif %}#}
{#        <div class="caption">#}
{#            <h4>{{ category.title }}</h4>#}
{#        </div>#}
{#    </a>#}
{#    </div>#}
{#    {% endfor %}#}
{#{% else %}#}
{#    {% for category in child_categories %}#}
{#    <div class="col-xs-6 col-sm-4 col-lg-3">#}
{#    <a href="{{ category.get_absolute_url }}" class="thumbnail">#}
{#        <div class="caption"><h4>{{ category.title }}</h4></div>#}
{#    </a>#}
{#    </div>#}
{#    {% endfor %}#}
{#{% endif %}#}
{#</div>#}
{#{% endif %}#}
{##}
{#{% if products.paginator.count != 0 %}#}
{##}
{#<form class="product-sorting" role="form">#}
{#    <div class="form-group">#}
{#    <label class="control-label" for="sorting-select">{% trans "Sort by" %}</label>#}
{#        <select onchange="location.href = this[this.selectedIndex].value;" class="form-control" id="sorting-select">#}
{#        {% for name, option in settings.SHOP_PRODUCT_SORT_OPTIONS %}#}
{#        {% if "rating" not in option or settings.SHOP_USE_RATINGS %}#}
{#        <option{% if option == products.sort_by %} selected{% endif %}#}
{#            value="{{ category.get_absolute_url }}?sort={{ option }}{{ querystring }}">#}
{#            {{ name }}#}
{#        </option>#}
{#        {% endif %}#}
{#        {% endfor %}#}
{#        </select>#}
{#    </div>#}
{#</form>#}
{##}
{#<div class="row product-list">#}
{#{% for product in products.object_list %}#}
{#    <div class="col-xs-6 col-sm-4 col-lg-3 product-thumb">#}
{#    <a href="{{ product.get_absolute_url }}" class="thumbnail">#}
{#        {% if product.image %}#}
{#        <img src="{{ MEDIA_URL }}{% thumbnail product.image 148 148 %}">#}
{#        {% else %}#}
{#        <div class="placeholder"></div>#}
{#        {% endif %}#}
{#        <div class="caption">#}
{#        <h6>{{ product }}</h6>#}
{#        <div class="price-info">#}
{#        {% if product.has_price %}#}
{#            {% if product.on_sale %}#}
{#            <span class="old-price">{{ product.unit_price|currency }}</span>#}
{#            {% trans "On sale:" %}#}
{#            {% endif %}#}
{#            <span class="price">{{ product.price|currency }}</span>#}
{#        {% else %}#}
{#            <span class="coming-soon">{% trans "Coming soon" %}</span>#}
{#        {% endif %}#}
{#        </div>#}
{#        </div>#}
{#    </a>#}
{#    </div>#}
{#{% endfor %}#}
{#</div>#}
{##}
{#{% pagination_for products %}#}
{##}
{#{% endif %}#}
{##}
{#{% endblock %}#}



{% load mezzanine_tags keyword_tags staticfiles pages_tags shopping_filters %}
{% block all_content %}
<!-- Content -->
  	<div class="content">
		<div class="product">
			<div class="product-menu">
				<h4>Thể Loại 2</h4>
                {% if categories %}
                    {% for category in child_categories %}
                        {% if forloop.first %}
                            <ul>
                        {% endif %}
                                <li><a href="#">{{ category.name }}</a></li>
                        {% if forloop.last %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endif %}
				<h4>Thể Loại 2</h4>
                {% if categories %}
                    {% for category in child_categories %}
                        {% if forloop.first %}
                            <ul>
                        {% endif %}
                                <li><a href="#">{{ category.name }}</a></li>
                        {% if forloop.last %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endif %}
				<h4>Thiết Kế Của Thành Viên</h4>
				<ul>
					<li><a href="#">Yêu thích nhất</a></li>
					<li><a href="#">Hình thiết kế</a></li>
				</ul>
				<h4 class="tit-color">Màu sắc</h4>
                <div class="list-color">
                    {% if color_list %}
                        {% for color in color_list %}
                            <a href="#" style="background: {{ color.name }}"></a>
                        {% endfor %}
                    {% endif %}
                </div>
			</div>
			<div class="product-content">
				<h4>MỚI NHẤT / YÊU THÍCH nhất</h4>
				<div class="product-list">
                    {% if products %}
                        {% for product in products %}
                            <div class="product-items">
                                <div class="sale-info">
                                    <span class="new">New</span>
                                    {% if product.on_sale %}
                                        <span class="sale">Sale</span>
                                    {% endif %}
                                </div>
                                <a href="{{ product.get_absolute_url }}">
                                    {% if product.image %}
                                        <img u="image" src="{{ MEDIA_URL }}{% thumbnail product.image 148 148 %}"  />
                                    {% else %}
                                        <div class="placeholder"></div>
                                    {% endif %}

                                </a>
                                <div class="product-info">
                                    <p class="name-product">{{ product.title }}</p>
                                    <p>Đăng bởi: </p> <span class="user-post">{{ product.user }}</span>
                                    {% if product.unit_price != product.sale_price %}
                                        <p>Giá: </p> <span class="price">{{ product.sale_price }}₫</span> <span class="price-old">{{ product.unit_price }}₫</span>
                                    {% else %}
                                        <p>Giá: </p> <span class="price">{{ product.unit_price }}₫</span>
                                    {% endif %}
                                {% with isLiked="is_liked"|add_str:product.id %}
{#                                        {{ request|get_cookies:isLiked }}#}
                                        {{ request|get_session:isLiked }}
                                        {% if user.is_authenticated %}
                                            <button id ="likes" data-productId="{{product.id}}" class="btn btn-mini btn-primary like-button" type="button">Like</button>
                                        {% endif %}
                                {% endwith %}
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}

					<div class="paging">
                        {% for i in products.paginator.num_pages|get_range %}
                            {% if products.number == i %}
                                <a href="javascript:void(0)" class="selected">{{ i }}</a>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                            {% if forloop.last %}
                            {% endif %}
                        {% endfor %}
                    </div>
				</div>
			</div>
		</div>
	</div>
	<!-- /. Content -->
    <script>
        $('.like-button').click(function(){
            var productId;
            productId = $(this).attr("data-productId");
            $.ajax({
                url: "{% url 'shopping:like_product' %}",
                type: "GET",
                data: {product_id: productId},
                success: function(data){
                    console.log(data);
                    $('#likes').hide();
                }
            })
        });

    </script>
{% endblock %}

wsgi/shopping/templates/pages/help - detail.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Intoidi</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/product.css">
<link rel="stylesheet" href="css/agile_carousel.css">



<!-- Latest compiled and minified JavaScript -->
<script type="text/javascript" src="js/jquery-1.10.1.min.js"></script>
<script type="text/javascript" src="js/jssor.js"></script>
<script type="text/javascript" src="js/jssor.slider.min.js"></script>
<script type="text/javascript" src="js/resize-home.js"></script>
<script type="text/javascript" src="js/resize.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">/*<![CDATA[*/var map;function initialize(){var a=document.getElementById("map-canvas");map=new google.maps.Map(a,{center:new google.maps.LatLng(16.071455,108.213218),zoom:13,mapTypeId:google.maps.MapTypeId.ROADMAP});google.maps.event.addListenerOnce(map,"tilesloaded",addMarkers)}function addMarkers(){var g=map.getBounds();var d=g.getSouthWest();var b=g.getNorthEast();var c=b.lng()-d.lng();var e=b.lat()-d.lat();var f=new google.maps.LatLng(16.071455,108.213218);var a=new google.maps.Marker({position:f,map:map})}google.maps.event.addDomListener(window,"load",initialize);/*]]>*/</script>

</head>

<body>
	<div class="wrapper container-home container-fluid">
		<div class="main container">	
			<!-- Header -->
			<div class="header">
				<div class="shadow"></div>
				<div class="header-items">
					<a class="logo" href="#"><img src="images/logo.png"></a>
					<div class="nav">
						<ul>
							<li><a href="#">Create A Shirt</a> | </li>
							<li><a href="#">Product Catalog</a> | </li>
							<li><a href="#">Forum</a> | </li>
							<li><a href="#">Help</a> | </li>
							<li><a href="#">Cart <span class="cart-count">(0)</span></a> | </li>
							<li><a href="#">Account</a> | </li>
							<li><a href="#">Contact</a>  </li>
						</ul>
					</div>
				
				</div>
			</div>
			<!-- /. Header -->	
			<!-- Content -->
		  	<div class="content">
				<div class="help">
					<h4>Help Center</h4>
					<div class="help-content">
						<div class="help-items help-general">
							<a href="#" class="btn-back"></a>
							<h5 class="help-title">General Info</h5>
							<a href="#">Shipping & Delivery</a>
							<a href="#">Payment Options</a>
							<a href="#">FAQ</a>
							<a href="#">Money Back Guarantee</a>
							<a href="#">Contact Us</a>
						</div>
						<div class="help-detail">
							<h4>Contact Us</h4>
							<div id="map-canvas" class="help-map">
								
							</div>
							<div class="help-address">
								<div class="help-address-items">
									<h5>Call Us</h5>
									<p>0935.288.448</p> 
									<p>Monday - Friday, 9am - 8pm Eastern Time</p> 
									<p>Saturday & Sunday, 9am - 5pm Eastern Time</p> 
								</div>
								<div class="help-address-items">
									<h5>Address</h5>									
									<p>190/5 Ông Ích Khiêm</p> 
									<p>P. Tân Chính, Q. Thanh Khê,</p>  
									<p>TP. Đà Nẵng</p>
								</div>
							</div>
						</div>
					</div>	
				</div>
			</div>
			<!-- /. Content -->

			<!-- Footer -->
			<div class="footer">
				<div class="footer-content">
			  		<div class="footer-items footer-items-add">
			  			<h6>Suport – We're here for you!</h6>
			  			<p class="phone">0935 288 488</p>
			  			<p class="email"> <a href="mailto:hotro@intoidi.com"> hotro@intoidi.com</a></p>
			  			<p class="address">190 Ông ích khiêm - Đà Nẵng</p>
			  		</div>
			  		<div class="footer-items">
			  			<h6>We promise</h6>
			  			<a href="#">30 Day Exchange Policy</a>
			  			<a href="#">Delivery in 3-7 working days</a>
			  			<a href="#">High quality printing</a>
			  			<a href="#">Cards accepted</a>
			  		</div>
			  		<div class="footer-items footer-items-information">
			  			<h6>Information</h6>
			  			<a href="#">Contact us</a>
			  			<a href="#">My orders</a>
			  			<a href="#">Wash Instruction</a>
			  			<a href="#">Sitemap</a>
			  		</div>
			  		<div class="footer-items footer-items-subscribe">
			  			<h6>Our Newsletter</h6>
			  			<input type="text" placeholder="Email" class="subs">
			  			<a href="" class="subscribe">Subscribe</a>
			  		</div>
			  		<div class="footer-items footer-items-social">
			  			<h6>Follow us</h6>
			  			<a href="#" class="face"></a>
			  			<a href="#" class="twi"></a>
			  			<a href="#" class="google"></a>
			  		</div>
			  		<div class="language">
			  			<a href="#" class="vi" title="Vietnamese"></a>
			  			<a href="#" class="en" title="English"></a>
			  		</div>
			  		<a href="#" class="copyright">Copyright © 2014 intoidi.com</a>
				</div>
			</div>
			<!-- /. Footer -->
		</div>
	</div>
</body>
</html>

wsgi/shopping/templates/pages/page.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags %}

{% block meta_title %}{{ page.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% endblock %}

{% block main %}
{% endblock %}

wsgi/shopping/templates/pages/product.html
{% extends "pages/page.html" %}
{% load mezzanine_tags keyword_tags staticfiles pages_tags shopping_filters %}
{% block all_content %}
<!-- Content -->
  	<div class="content">
		<div class="product">
			<div class="product-menu">
				<h4>Thể Loại 2</h4>
                {% if categories %}
                    {% for category in categories %}
                        {% if forloop.first %}
                            <ul>
                        {% endif %}
                                <li><a href="#">{{ category.name }}</a></li>
                        {% if forloop.last %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endif %}
				<h4>Thể Loại 2</h4>
                {% if categories %}
                    {% for category in categories %}
                        {% if forloop.first %}
                            <ul>
                        {% endif %}
                                <li><a href="#">{{ category.name }}</a></li>
                        {% if forloop.last %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endif %}
				<h4>Thiết Kế Của Thành Viên</h4>
				<ul>
					<li><a href="#">Yêu thích nhất</a></li>
					<li><a href="#">Hình thiết kế</a></li>							
				</ul>
				<h4 class="tit-color">Màu sắc</h4>
                <div class="list-color">
                    {% if color_list %}
                        {% for color in color_list %}
                            <a href="#" style="background: {{ color.name }}"></a>
                        {% endfor %}
                    {% endif %}
                </div>
{#				<div class="list-color">#}
{#					<a href="#" class="cl-brown"></a>#}
{#					<a href="#" class="cl-red"></a>#}
{#					<a href="#" class="cl-orange"></a>#}
{#					<a href="#" class="cl-white"></a>#}
{#					<a href="#" class="cl-purple"></a>#}
{#					<a href="#" class="cl-blue active"></a>#}
{#					<a href="#" class="cl-yellow"></a>#}
{#					<a href="#" class="cl-green"></a>#}
{#					<a href="#" class="cl-green1"></a>#}
{#					<a href="#" class="cl-green2"></a>#}
{#					<a href="#" class="cl-pink"></a>#}
{#				</div>#}
			</div>
			<div class="product-content">
				<h4>MỚI NHẤT / YÊU THÍCH nhất</h4>
				<div class="product-list">
                    {% if products %}
                        {% for product in products %}
                            <div class="product-items">
                                <div class="sale-info">
                                    <span class="new">New</span>
                                    {% if product.unit_price != product.sale_price %}
                                        <span class="sale">Sale</span>
                                    {% endif %}
                                </div>
                                <a href="{% url 'shopping:detail' product.id %}"><img u="image" src="{{ MEDIA_URL }}{{ product_image_list|get_at_index:forloop.counter0 }}"  /></a>
                                <div class="product-info">
                                    <p class="name-product">{{ product.title }}</p>
                                    <p>Đăng bởi: </p> <span class="user-post">{{ product.user }}</span>
                                    {% if product.unit_price != product.sale_price %}
                                        <p>Giá: </p> <span class="price">{{ product.sale_price }}₫</span> <span class="price-old">{{ product.unit_price }}₫</span>
                                    {% else %}
                                        <p>Giá: </p> <span class="price">{{ product.unit_price }}₫</span>
                                    {% endif %}
                                {% with isLiked="is_liked"|add_str:product.id %}
{#                                        {{ request|get_cookies:isLiked }}#}
                                        {{ request|get_session:isLiked }}
                                        {% if user.is_authenticated %}
                                            <button id ="likes" data-productId="{{product.id}}" class="btn btn-mini btn-primary like-button" type="button">Like</button>
                                        {% endif %}
                                {% endwith %}
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
{#					<div class="product-items">#}
{#						<a href="#"><img u="image" src="{% static "images/product4.jpg" %}" /></a>#}
{#		           		#}
{#		           		<div class="product-info">#}
{#		           			<p class="name-product">Tên sản phẩm</p>#}
{#			           		<p>Đăng bởi: </p> <span class="user-post"> member</span>#}
{#			           		<p>Giá: </p> <span class="price">199,000₫</span> #}
{#		           		</div>#}
{#					</div>#}
{#					<div class="clear-fix"></div>#}

					<div class="paging">
                        {% for i in products.paginator.num_pages|get_range %}
                            {% if products.number == i %}
                                <a href="javascript:void(0)" class="selected">{{ i }}</a>
                            {% else %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endif %}
                            {% if forloop.last %}
                            {% endif %}
                        {% endfor %}
{#                        <a href="#" class="selected">1</a><a href="#">2</a><a href="#">3</a><a href="#">&gt;</a>#}
                    </div>
				</div>
			</div>
		</div>	
	</div>
	<!-- /. Content -->
    <script>
        $('.like-button').click(function(){
            var productId;
            productId = $(this).attr("data-productId");
            $.ajax({
                url: "{% url 'shopping:like_product' %}",
                type: "GET",
                data: {product_id: productId},
                success: function(data){
                    console.log(data);
                    $('#likes').hide();
                }
            })
        });

    </script>
{% endblock %}